### ISSUE TITLE
QFileDialog does not show device files when browsing for sniffers

### ISSUE THREAD

**Issue by cgundogan** [cetic/foren6-gui-qt#1]
When I browse for a sniffer using the _Manage Sources_ dialog, I cannot see any device files in the **/dev** directory. I compiled foren6 under (arch) linux.
After some googling I read about similar cases (not related to foren6), that the **QFileDialog** may ignore (character) device files? Is anyone else facing such a problem?

**Comment by laurentderu** [comment]
We face the same issue, the QFileDialog does not display special files, we have the same problem with FIFOs.

**Comment by laurentderu** [comment]
PR merged since a long time.
